#!/usr/bin/env python3
"""Train an offline IQL-style policy on rl_dataset transitions.

This script is intentionally self-contained (PyTorch only) and targets the dataset
generated by `tools/build_rl_dataset.py`.

It trains a deterministic actor via advantage-weighted regression (AWR-style),
plus Q/V critics trained with an IQL expectile value objective.

Recommended usage (train/val split is random by default):

  python3 rl/train_iql.py \
    --dataset rl_dataset/transitions.npz \
    --outdir models/iql

If you need strict split by trace_id, consider extending the dataset builder
to persist meta arrays in the NPZ, or train from transitions.csv and split by
(trace_id, client_id).
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F


# Dataset columns are fixed by our generator.
STATE_ORDER = ["send_bps", "recv_bps", "rtt_ms", "loss_rate", "jitter_ms"]


@dataclass
class NormConfig:
    obs_mean: np.ndarray
    obs_std: np.ndarray
    a_min: float
    a_max: float

    # feature transforms
    bps_scale: float = 1e5


def transform_obs(obs: np.ndarray, *, cfg: NormConfig) -> np.ndarray:
    """Apply log transforms + standardization.

    obs shape: (..., 5) in STATE_ORDER.
    """

    obs = obs.astype(np.float32, copy=False)
    send_bps = np.log1p(np.maximum(obs[..., 0], 0.0) / cfg.bps_scale)
    recv_bps = np.log1p(np.maximum(obs[..., 1], 0.0) / cfg.bps_scale)
    rtt = np.log1p(np.maximum(obs[..., 2], 0.0))
    loss = np.clip(obs[..., 3], 0.0, 1.0)
    jitter = np.log1p(np.maximum(obs[..., 4], 0.0))

    x = np.stack([send_bps, recv_bps, rtt, loss, jitter], axis=-1)
    x = (x - cfg.obs_mean) / (cfg.obs_std + 1e-6)
    return x.astype(np.float32, copy=False)


def inverse_action(a_norm: np.ndarray, *, cfg: NormConfig) -> np.ndarray:
    a_norm = np.clip(a_norm, -1.0, 1.0)
    return cfg.a_min + (a_norm + 1.0) * 0.5 * (cfg.a_max - cfg.a_min)


def normalize_action(a_bps: np.ndarray, *, cfg: NormConfig) -> np.ndarray:
    a = (a_bps - cfg.a_min) / max(cfg.a_max - cfg.a_min, 1e-6)
    return (a * 2.0 - 1.0).astype(np.float32, copy=False)


class MLP(nn.Module):
    def __init__(self, in_dim: int, out_dim: int, hidden: int = 256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden),
            nn.ReLU(),
            nn.Linear(hidden, hidden),
            nn.ReLU(),
            nn.Linear(hidden, out_dim),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class DeterministicActor(nn.Module):
    def __init__(self, obs_dim: int, hidden: int = 256):
        super().__init__()
        self.backbone = nn.Sequential(
            nn.Linear(obs_dim, hidden),
            nn.ReLU(),
            nn.Linear(hidden, hidden),
            nn.ReLU(),
            nn.Linear(hidden, 1),
        )

    def forward(self, obs: torch.Tensor) -> torch.Tensor:
        # output in [-1, 1]
        return torch.tanh(self.backbone(obs))


def expectile_loss(diff: torch.Tensor, expectile: float) -> torch.Tensor:
    # diff = q - v
    weight = torch.where(diff > 0, expectile, 1.0 - expectile)
    return (weight * diff.pow(2)).mean()


def soft_update(target: nn.Module, source: nn.Module, tau: float) -> None:
    with torch.no_grad():
        for t, s in zip(target.parameters(), source.parameters()):
            t.data.mul_(1.0 - tau)
            t.data.add_(s.data, alpha=tau)


def load_npz(path: Path) -> dict[str, np.ndarray]:
    data = np.load(path, allow_pickle=True)
    return {k: data[k] for k in data.files}


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--dataset", type=str, default="rl_dataset/transitions.npz")
    p.add_argument("--outdir", type=str, default="models/iql")

    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--train-ratio", type=float, default=0.9)

    p.add_argument("--steps", type=int, default=300_000)
    p.add_argument("--batch", type=int, default=256)

    p.add_argument("--gamma", type=float, default=0.99)
    p.add_argument("--expectile", type=float, default=0.7)
    p.add_argument("--beta", type=float, default=3.0)

    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--target-tau", type=float, default=0.005)
    p.add_argument("--grad-clip", type=float, default=1.0)

    p.add_argument("--device", type=str, default="cpu")

    args = p.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    dataset_path = Path(args.dataset)
    data = load_npz(dataset_path)

    obs_raw = data["observations"].astype(np.float32)
    next_obs_raw = data["next_observations"].astype(np.float32)
    actions_bps = data["actions"].astype(np.float32)
    rewards = data["rewards"].astype(np.float32)
    dones = data["terminals"].astype(np.float32)

    n = obs_raw.shape[0]
    if n < 1024:
        raise SystemExit(f"dataset too small: {n}")

    # action bounds from dataset (slightly expanded)
    a_min = float(np.percentile(actions_bps, 1))
    a_max = float(np.percentile(actions_bps, 99.5))
    a_min = max(1.0, a_min * 0.95)
    a_max = max(a_min + 1.0, a_max * 1.05)

    # temporary cfg to compute mean/std on transformed features
    tmp_cfg = NormConfig(obs_mean=np.zeros(5, dtype=np.float32), obs_std=np.ones(5, dtype=np.float32), a_min=a_min, a_max=a_max)
    obs_t = transform_obs(obs_raw, cfg=tmp_cfg)

    # split indices
    perm = np.random.permutation(n)
    n_train = int(n * float(args.train_ratio))
    train_idx = perm[:n_train]
    val_idx = perm[n_train:]

    obs_mean = obs_t[train_idx].mean(axis=0)
    obs_std = obs_t[train_idx].std(axis=0) + 1e-6

    cfg = NormConfig(obs_mean=obs_mean.astype(np.float32), obs_std=obs_std.astype(np.float32), a_min=a_min, a_max=a_max)

    obs = transform_obs(obs_raw, cfg=cfg)
    next_obs = transform_obs(next_obs_raw, cfg=cfg)
    act = normalize_action(actions_bps, cfg=cfg).reshape(-1, 1)

    device = torch.device(args.device)

    obs_torch = torch.from_numpy(obs).to(device)
    next_obs_torch = torch.from_numpy(next_obs).to(device)
    act_torch = torch.from_numpy(act).to(device)
    rew_torch = torch.from_numpy(rewards.reshape(-1, 1)).to(device)
    done_torch = torch.from_numpy(dones.reshape(-1, 1)).to(device)

    obs_dim = obs_torch.shape[1]

    q1 = MLP(obs_dim + 1, 1).to(device)
    q2 = MLP(obs_dim + 1, 1).to(device)
    v = MLP(obs_dim, 1).to(device)
    v_tgt = MLP(obs_dim, 1).to(device)
    v_tgt.load_state_dict(v.state_dict())

    actor = DeterministicActor(obs_dim).to(device)

    opt_q = torch.optim.Adam(list(q1.parameters()) + list(q2.parameters()), lr=args.lr)
    opt_v = torch.optim.Adam(v.parameters(), lr=args.lr)
    opt_pi = torch.optim.Adam(actor.parameters(), lr=args.lr)

    def q_forward(model: nn.Module, o: torch.Tensor, a: torch.Tensor) -> torch.Tensor:
        return model(torch.cat([o, a], dim=-1))

    train_idx_torch = torch.from_numpy(train_idx).to(device)
    val_idx_torch = torch.from_numpy(val_idx).to(device)

    best_val = float("inf")
    best_step = -1

    for step in range(1, int(args.steps) + 1):
        idx = train_idx_torch[torch.randint(0, train_idx_torch.shape[0], (args.batch,), device=device)]

        o = obs_torch[idx]
        o1 = next_obs_torch[idx]
        a = act_torch[idx]
        r = rew_torch[idx]
        d = done_torch[idx]

        with torch.no_grad():
            target_v1 = v_tgt(o1)
            y = r + args.gamma * (1.0 - d) * target_v1

        # Q update
        q1_pred = q_forward(q1, o, a)
        q2_pred = q_forward(q2, o, a)
        q_loss = F.mse_loss(q1_pred, y) + F.mse_loss(q2_pred, y)

        opt_q.zero_grad(set_to_none=True)
        q_loss.backward()
        if args.grad_clip > 0:
            nn.utils.clip_grad_norm_(list(q1.parameters()) + list(q2.parameters()), args.grad_clip)
        opt_q.step()

        # V update (expectile regression to min(Q))
        with torch.no_grad():
            q_min = torch.min(q_forward(q1, o, a), q_forward(q2, o, a))
        v_pred = v(o)
        v_loss = expectile_loss(q_min - v_pred, float(args.expectile))

        opt_v.zero_grad(set_to_none=True)
        v_loss.backward()
        if args.grad_clip > 0:
            nn.utils.clip_grad_norm_(v.parameters(), args.grad_clip)
        opt_v.step()

        # Actor update (advantage-weighted regression to dataset actions)
        with torch.no_grad():
            v_detached = v(o)
            q_min2 = torch.min(q_forward(q1, o, a), q_forward(q2, o, a))
            adv = q_min2 - v_detached
            w = torch.exp(adv * float(args.beta)).clamp(max=100.0)

        a_pred = actor(o)
        pi_loss = (w * (a_pred - a).pow(2)).mean()

        opt_pi.zero_grad(set_to_none=True)
        pi_loss.backward()
        if args.grad_clip > 0:
            nn.utils.clip_grad_norm_(actor.parameters(), args.grad_clip)
        opt_pi.step()

        # target update
        soft_update(v_tgt, v, float(args.target_tau))

        if step % 2000 == 0 or step == 1:
            with torch.no_grad():
                # validation: weighted MSE against data actions (proxy)
                vidx = val_idx_torch
                o_v = obs_torch[vidx]
                a_v = act_torch[vidx]
                a_v_pred = actor(o_v)
                val_mse = F.mse_loss(a_v_pred, a_v).item()

            print(
                f"step={step} q={q_loss.item():.4f} v={v_loss.item():.4f} pi={pi_loss.item():.4f} val_mse={val_mse:.6f}",
                flush=True,
            )

            if val_mse < best_val:
                best_val = val_mse
                best_step = step
                torch.save(actor.state_dict(), outdir / "actor.pt")
                torch.save({"q1": q1.state_dict(), "q2": q2.state_dict(), "v": v.state_dict()}, outdir / "critics.pt")
                with (outdir / "norm.json").open("w", encoding="utf-8") as f:
                    json.dump(
                        {
                            "state_order": STATE_ORDER,
                            "obs_mean": cfg.obs_mean.tolist(),
                            "obs_std": cfg.obs_std.tolist(),
                            "bps_scale": cfg.bps_scale,
                            "a_min": cfg.a_min,
                            "a_max": cfg.a_max,
                        },
                        f,
                        ensure_ascii=False,
                        indent=2,
                    )

    print(f"best checkpoint: step={best_step} val_mse={best_val:.6f}")


if __name__ == "__main__":
    main()
